attendance/attendance/urls.py
from django.urls import path, include # 追加
from . import views

app_name = 'attendance'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.EnterTimeView.as_view(), name='index'), # 時間入力画面
    path('<str:day>', views.EnterTimeView.as_view(), name='day'),
    path('accounts/', include('django.contrib.auth.urls')), #
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('regist/', views.regist, name='regist'),
    path('daysearch/<str:day>', views.daysearch, name='daysearch'),
    path('historylist/', views.HistoryListView.as_view(), name='historylist'), # 勤務時間確認画面
    path('historysearch/', views.search, name='search'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('historyremove/<str:id>', views.historyremove, name='historyremove'),
]

attendance/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('attendance/', include('attendance.urls')),
    path('', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

attendance/attendance/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
# Create your models here.

class Holiday(models.Model):
    month = models.IntegerField(verbose_name='月')
    holiday_count = models.IntegerField(verbose_name='休日数', default=0)

class History(models.Model):
    user_id = models.IntegerField(verbose_name='ユーザID')
    date = models.DateField(verbose_name='日時')
    start_time = models.TimeField(verbose_name='開始時間')
    end_time = models.TimeField(verbose_name=' 終了時間')
    paid = models.DecimalField(verbose_name='有休数', max_digits=3, decimal_places=1, default=0.0)

    def regist_history(add_user_id, add_date, add_start, add_end, add_paid):
        strdate = add_date.replace('/', '-')
        # h = History.objects.get(user_id=add_user_id, date=strdate)
        # print(h.end_time)
        # return History.objects.create(user_id=add_user_id, date=strdate, start_time=add_start, end_time=add_end, paid=add_paid)

        return History.objects.update_or_create(
            # ユニークな値
            user_id=add_user_id, date=strdate,
            # 更新もしくは新規で追加したい値
            defaults={
                "user_id": add_user_id,
                "date": strdate,
                "start_time": add_start,
                "end_time": add_end,
                "paid": add_paid
            },
        )

    def remove_history(id):
        return History.objects.filter(id=id).delete()


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a user with the given username, email, and
        password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    #有休数
    paid = models.DecimalField(verbose_name='有休数', max_digits=3, decimal_places=1, default=0.0)

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

attendance/attendance/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model
from .models import Holiday
from .models import History
from .models import User
from django.core.cache import cache
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

import calendar
import datetime
import datetime as dt

# ログアウト
class LogoutView(TemplateView):
    def get(self, *args, **kwargs):
        logout(self.request)
        url = reverse('attendance:login')
        # return redirect('attendance:login')
        return HttpResponseRedirect(url)

# 時間入力画面
class EnterTimeView(TemplateView):
    template_name = "attendance/entertime.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す

        # 現在日時取得
        strdate = '{0:%Y-%m-%d}'.format(datetime.datetime.now()) #test_20170910
        day = self.kwargs.get('day')
        if day is not None:
            strdate = day

        try:
            obj = History.objects.get(user_id=self.request.user.id, date=strdate)
            params = { # <- 渡したい変数を辞書型オブジェクトに格納
                # 'start': obj.start_time,
                'start': obj.start_time.strftime('%H:%M'),
                # 'end': obj.end_time,
                'end': obj.end_time.strftime('%H:%M'),
                'paid': obj.paid,
                'day': strdate
            }
            context=params
            return context

        except History.DoesNotExist:
            params = {
                'day': strdate
            }
            context=params
            return context

class DetailView(generic.DetailView):
    model = Holiday
    template_name = 'attendance/detail.html'


class ResultsView(generic.DetailView):
    model = Holiday
    template_name = 'attendance/results.html'


def daysearch(request, day):
    url = reverse('attendance:day', kwargs={'day': day})
    print(url)
    return HttpResponseRedirect(url)

def regist(request):
    History.regist_history(request.user.id, request.POST['day'], request.POST['start'], request.POST['end'], request.POST['paid'])
    url = reverse('attendance:day', kwargs={'day': request.POST['day']})
    print(url)
    return HttpResponseRedirect(url)

def historyremove(request, id):
    # cache.set('day', day, 60 * 15)  # cache in 15 minutes
    History.remove_history(id)
    return HttpResponseRedirect(reverse('attendance:historylist'))

def get_h_m_s(td):
    m, s = divmod(td.seconds, 60)
    h, m = divmod(m, 60)
    return h, m, s


# 勤務時間確認画面
class HistoryListView(TemplateView):
    model = History
    template_name = "attendance/historylist.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す

        #有給日数
        context['paid'] = self.request.user.paid
        history_list = self.model.objects.all().order_by('date')

        #年月指定があった場合は現在日時を使用
        strdate = '{0:%Y-%m-%d}'.format(datetime.datetime.now())
        context['yearmonth'] = strdate.split('-')[0] + '-' + strdate.split('-')[1]
        #年月指定があった場合はフィルタ指定
        if self.request.GET.get('date') is not None:
            strdate = self.request.GET.get('date')
            context['yearmonth'] = strdate

        hislist = []
        object_list =history_list.filter(date__year=strdate.split('-')[0], date__month=strdate.split('-')[1])
        # context['history_list'] = object_list

        #合計時間
        totalworktime = 0
        requiredworkday = 0

        for history in object_list:
            day = history.date.strftime('%Y-%m-%d') + " "

            #業務開始時間
            strstart = day + history.start_time.strftime('%H:%M:%S.000') # 日付を文字列
            start_time = dt.datetime.strptime(strstart, "%Y-%m-%d %H:%M:%S.000") # 文字列を日付
            #業務終了時間
            strend = day + history.end_time.strftime('%H:%M:%S.000')
            end_time = dt.datetime.strptime(strend, "%Y-%m-%d %H:%M:%S.000")

            #昼休憩開始時間
            strlbstart = day + "12:30:00"
            lbstart_time = dt.datetime.strptime(strlbstart, "%Y-%m-%d %H:%M:%S")
            #昼休憩終了時間
            strlbend = day + "13:30:00"
            lbend_time = dt.datetime.strptime(strlbend, "%Y-%m-%d %H:%M:%S")

            #労働時間
            worktime = end_time - start_time

            #通常
            if lbstart_time >= start_time and end_time >= lbend_time:
                worktime = worktime - datetime.timedelta(hours=1) #1時間減算
            #午前半休パターン
            elif lbstart_time >= start_time and end_time <= lbend_time:
                worktime = worktime - (end_time - lbstart_time) #12:30以降の時間減算
            #午後半休パターン
            elif lbstart_time <= start_time and end_time >= lbend_time:
                worktime = worktime - (lbend_time - start_time) #12:30以前の時間減算

            #夕憩開始時間
            strebstart = day + "18:00:00"
            ebstart_time = dt.datetime.strptime(strebstart, "%Y-%m-%d %H:%M:%S")
            #夕憩終了時間
            strebend = day + "18:15:00"
            ebend_time = dt.datetime.strptime(strebend, "%Y-%m-%d %H:%M:%S")

            #通常
            if ebstart_time >= start_time and end_time >= ebend_time:
                worktime = worktime - datetime.timedelta(minutes=15) #15分減算
            #18:00から18:15の間に退勤した場合
            elif end_time >= ebstart_time and end_time <= ebend_time:
                worktime = worktime - (end_time - ebstart_time) #18:15までの時間を減算

            #半有給の場合は実働に3:45を加算
            if history.paid == 0.5:
                worktime = worktime + datetime.timedelta(hours=3)
                worktime = worktime + datetime.timedelta(minutes=45)

            totalworktime = totalworktime + worktime.total_seconds()

            #稼働時間
            h, m, s = get_h_m_s(worktime)
            if m < 10:
                strWork = str(h) + ":0" + str(m)
            else:
                strWork = str(h) + ":" + str(m)
            history.daytime = strWork

            hislist.append(history)

            #コアタイム開始時間
            strcorestart = day + "10:30:00"
            corestart_time = dt.datetime.strptime(strcorestart, "%Y-%m-%d %H:%M:%S")
            #コアタイム終了時間
            # strcoreend = day + "15:30:00"
            strcoreend = day + "14:30:00" #育児のため時種変、コアタイム15:30 -> 14:30
            coreend_time = dt.datetime.strptime(strcoreend, "%Y-%m-%d %H:%M:%S")
            #出勤日数加算
            if history.paid == 0.0 and corestart_time < start_time and coreend_time < end_time:
                requiredworkday = requiredworkday + 0.5
            elif history.paid == 0.0 and corestart_time > start_time and coreend_time > end_time:
                requiredworkday = requiredworkday + 0.5
            else:
                requiredworkday = requiredworkday + 1

        context['history_list'] = hislist

        #選択月のに数を取得
        _, lastday = calendar.monthrange(int(strdate.split('-')[0]),int(strdate.split('-')[1]))

        #休日数取得
        holiday = Holiday.objects.get(month=int(strdate.split('-')[1]))

        #必要出勤日数算出
        context['workday'] = lastday - holiday.holiday_count

        #選択月休日数
        context['holidaycount'] = holiday.holiday_count

        #出勤日数算出
        # context['requiredworkday'] = len(object_list)
        context['requiredworkday'] = requiredworkday

        #出勤日数差分算出
        context['workdaydiff'] = lastday - holiday.holiday_count - requiredworkday

        #実労働時間算出
        td = datetime.timedelta(seconds=totalworktime)
        h, m, s = get_h_m_s(td)
        strColon = ":"
        if m < 10:
            strColon = ":0"

        context['requiredtime'] = str(h + 24 * td.days) + strColon + str(m)


        #必要労働時間算出
        worktime = datetime.timedelta(hours=7)
        worktime = worktime + datetime.timedelta(minutes=30)
        worktime = worktime * (lastday - holiday.holiday_count)
        h, m, s = get_h_m_s(worktime)
        strColon = ":"
        if m < 10:
            strColon = ":0"
        context['worktime'] = str(h + 24 * worktime.days) + strColon + str(m)

        #労働時間過不足算出
        worktimediff = worktime - td
        h, m, s = get_h_m_s(worktimediff)

        if h + 24 * worktimediff.days < 0:
            worktimediff = td - worktime
            h, m, s = get_h_m_s(worktimediff)
            strColon = ":"
            if m < 10:
                strColon = ":0"
            context['worktimediff'] = "超過" + str(h + 24 * worktimediff.days) + strColon + str(m)

        else:
            strColon = ":"
            if m < 10:
                strColon = ":0"
            context['worktimediff'] = str(h + 24 * worktimediff.days) + strColon + str(m)

        return context

# 勤怠一覧取得
def search(search):

    return HttpResponseRedirect(reverse('attendance:historylist'))

attendance/attendance/templates/attendance/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'attendance:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

attendance/attendance/templates/attendance/entertime.html
<!-- 時間入力画面 -->

{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% if user.is_authenticated %}

<script src="{% static 'bootstrap/js/jquery-3.3.1.min.js' %}"></script>
<script>
  function handler(e){
    window.location.href = "/attendance/daysearch/" + e.target.value;
  }
</script>

<form action="{% url 'attendance:regist' %}" method="post">
  {% csrf_token %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" /> <!-- bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'attendance/style.css' %}">
  <body>
    <!-- Page Content -->
    <div class="container">
      <h4 class="mt-5">時間入力画面</h4>
      </br>
      <!-- 日付入力 -->
      <input type="date" class="form-control" style="width:200px;" name="day" value={% if day %}{{ day }}{% else %}{% now "Y-m-d" %}{% endif %} onchange="handler(event);"></br>
      出勤時間</br>
      <input type="time" class="form-control" style="width:200px;" size="30" name="start" value={% if start %}{{ start }}{% else %}09:30{% endif %}></br>
      退勤時間</br>
      <input type="time" class="form-control" style="width:200px;" size="30" name="end" value={% if end %}{{ end }}{% else %}18:00{% endif %}></br>
      ※有給半日の場合は実労働時間を入力、有給１日の場合は9:30〜18:00を入力する。
      </br></br>休暇種別</br>
      <div class="radio">
        <div><label><input type="radio" name="paid" value=0 {% if paid == '' or paid == 0.0 or paid == None %}checked="checked"{% endif %}> 利用なし</label></div>
        <div><label><input type="radio" name="paid" value=11 {% if paid == 11 %}checked="checked"{% endif %}> 特別休暇</label></div>
        <div><label><input type="radio" name="paid" value=1 {% if paid == 1.0 %}checked="checked"{% endif %}> 有給１日</label></div>
        <div><label><input type="radio" name="paid" value=0.5 {% if paid == 0.5 %}checked="checked"{% endif %}> 有給半日</label></div>
      </div>
      </br>
      <input type="submit" value="更新">
    </div>
</br></br>
  </body>
</form>

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'attendance:login' %}">login</a>
{% endif %}
{% endblock %}

attendance/attendance/templates/attendance/historylist.html
<!-- 　勤務時間確認画面 -->
{% extends 'base.html' %}
{% block content %}
{% load attendance_history_filters %}
{% if user.is_authenticated %}
{% load staticfiles %}

<form method="get" action="" name="filter_form">
  {% csrf_token %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" /> <!-- bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'attendance/style.css' %}">
  <body>
    <!-- Page Content -->
    <div class="container">
      <h4 class="mt-5">勤務時間確認</h4>
      </br>
      年月選択</br>
      <input type="month" class="form-control" style="width:200px;" id="filter_date" name="date" value={{ yearmonth }} onchange="submit(this.form)">
      </br>
      選択月休日数：{{ holidaycount }}</br>
      有給残日数：{{ paid }}</br>
      必要出勤日数：{{ workday }}</br>
      出勤日数（過不足）：{{ requiredworkday }}（{{ workdaydiff }}）</br>
      必要労働時間：{{ worktime }}</br>
      実労働時間（過不足）：{{ requiredtime }}（{{ worktimediff }}）</br>
      </br>
      勤務時間一覧</br>
      {% if history_list %}
        <table class="table table-striped">
          <tr>
            <th>日付</th>
            <th>開始時間</th>
            <th>終了時間</th>
            <th>休暇種別</th>
            <th>稼働時間</th>
            <th>　</th>
          </tr>
          {% for history in history_list %}
          <tr>
            <td>{{ history.date }} ( {% if history.date.weekday == 0 %}月{% elif history.date.weekday == 1 %}火{% elif history.date.weekday == 2 %}水{% elif history.date.weekday == 3 %}木{% elif history.date.weekday == 4 %}金{% elif history.date.weekday == 5 %}土{% elif history.date.weekday == 6 %}日{% endif %} )</td>
            <td>{{ history.start_time }}</td>
            <td>{{ history.end_time }}</td>
            <td>{% if history.paid == 11.0 %}特別休暇{% elif history.paid == 1.0 %}有給{% elif history.paid == 0.5 %}半日有給{% else %}利用なし{% endif %}</td>
            <td>{{ history.daytime }}</td>
            <td><a href="/attendance/historyremove/{{ history.id }}">削除</a></td>
          </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>履歴なし</p>
      {% endif %}
    </div>
  </body>
</form>

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'attendance:login' %}">login</a>
{% endif %}
{% endblock %}

attendance/attendance/templates/attendance/index.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.last_name }}!</br>

  {% now "F" %}{% now "j" %}日</br>

  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'attendance/style.css' %}">
  {% if latest_holiday_list %}
      <ul>
      {% for holiday in latest_holiday_list %}
        <li><a href="{% url 'attendance:detail' holiday.month %}">{{ holiday.month }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>No attendance are available.</p>
  {% endif %}


  <p><a href="{% url 'attendance:logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'attendance:login' %}">login</a>
{% endif %}
{% endblock %}

attendance/attendance/templates/attendance/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'attendance:detail' question.id %}">Vote again?</a>